package com.ubi.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.articleid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Long articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.titile
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String titile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.deploytime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Date deploytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.validtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Date validtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.label
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.visits
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Long visits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.articletype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Byte articletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.projecttype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Byte projecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.cityid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.srouce
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String srouce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.sourceurl
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String sourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.summary
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.createtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.updatetime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.content
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    private String content;

    private String provinceid;

    private String provincename;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.articleid
     *
     * @return the value of tb_article.articleid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.articleid
     *
     * @param articleid the value for tb_article.articleid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.titile
     *
     * @return the value of tb_article.titile
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.titile
     *
     * @param titile the value for tb_article.titile
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setTitile(String titile) {
        this.titile = titile == null ? null : titile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.deploytime
     *
     * @return the value of tb_article.deploytime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Date getDeploytime() {
        return deploytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.deploytime
     *
     * @param deploytime the value for tb_article.deploytime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setDeploytime(Date deploytime) {
        this.deploytime = deploytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.validtime
     *
     * @return the value of tb_article.validtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Date getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.validtime
     *
     * @param validtime the value for tb_article.validtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setValidtime(Date validtime) {
        this.validtime = validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.label
     *
     * @return the value of tb_article.label
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.label
     *
     * @param label the value for tb_article.label
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.visits
     *
     * @return the value of tb_article.visits
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Long getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.visits
     *
     * @param visits the value for tb_article.visits
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setVisits(Long visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.articletype
     *
     * @return the value of tb_article.articletype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Byte getArticletype() {
        return articletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.articletype
     *
     * @param articletype the value for tb_article.articletype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setArticletype(Byte articletype) {
        this.articletype = articletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.projecttype
     *
     * @return the value of tb_article.projecttype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Byte getProjecttype() {
        return projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.projecttype
     *
     * @param projecttype the value for tb_article.projecttype
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setProjecttype(Byte projecttype) {
        this.projecttype = projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.cityid
     *
     * @return the value of tb_article.cityid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.cityid
     *
     * @param cityid the value for tb_article.cityid
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.srouce
     *
     * @return the value of tb_article.srouce
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getSrouce() {
        return srouce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.srouce
     *
     * @param srouce the value for tb_article.srouce
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setSrouce(String srouce) {
        this.srouce = srouce == null ? null : srouce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.sourceurl
     *
     * @return the value of tb_article.sourceurl
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getSourceurl() {
        return sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.sourceurl
     *
     * @param sourceurl the value for tb_article.sourceurl
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl == null ? null : sourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.summary
     *
     * @return the value of tb_article.summary
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.summary
     *
     * @param summary the value for tb_article.summary
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.createtime
     *
     * @return the value of tb_article.createtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.createtime
     *
     * @param createtime the value for tb_article.createtime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.updatetime
     *
     * @return the value of tb_article.updatetime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.updatetime
     *
     * @param updatetime the value for tb_article.updatetime
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.content
     *
     * @return the value of tb_article.content
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.content
     *
     * @param content the value for tb_article.content
     *
     * @mbggenerated Mon Nov 20 16:58:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getProvincename() {
        return provincename;
    }

    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    @Override
    public String toString() {
        return "Article{" +
                "articleid=" + articleid +
                ", titile='" + titile + '\'' +
                ", deploytime=" + deploytime +
                ", validtime=" + validtime +
                ", label='" + label + '\'' +
                ", visits=" + visits +
                ", articletype=" + articletype +
                ", projecttype=" + projecttype +
                ", cityid=" + cityid +
                ", srouce='" + srouce + '\'' +
                ", sourceurl='" + sourceurl + '\'' +
                ", summary='" + summary + '\'' +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                ", content='" + content + '\'' +
                ", provinceid='" + provinceid + '\'' +
                ", provincename='" + provincename + '\'' +
                '}';
    }
}